import sqlglot
from sqlglot import expressions as exp
from app.utils.logger import logger

class HarmoniaService:
    @staticmethod
    async def role_based_sql_filter(user_role: str, user_id: str, sql_query: str) -> str:
        role = user_role.lower().strip()

        # Admin: Return query unmodified
        if role == "admin":
            return sql_query

        # Parse SQL into AST
        try:
            parsed = sqlglot.parse_one(sql_query, read="postgres")
        except Exception as e:
            logger.error(f"[RBAC] Invalid SQL generated by LLM: {e}")
            raise ValueError(f"Invalid SQL generated by LLM: {e}")

        # NEW: Dynamically resolve main table alias to prevent AmbiguousColumnError
        from_table = parsed.find(exp.From)
        table_ref = from_table.find(exp.Table) if from_table else None
        table_alias = table_ref.alias_or_name if table_ref else None

        # Employee Role: Filter directly by GlobalUserId
        if role == "employee":
            if table_alias:
                condition = exp.column("GlobalUserId", table=table_alias).eq(exp.Literal.string(user_id))
            else:
                condition = exp.column("GlobalUserId").eq(exp.Literal.string(user_id))
                
            # append=True automatically combines with existing WHERE using AND
            parsed = parsed.where(condition, append=True)
            return parsed.sql(pretty=True, dialect="postgres")

        # Manager Role: Filter GlobalUserId IN (subquery from Manager_Master)
        if role == "manager":
            subquery = (
                exp.Select(
                    distinct=exp.Distinct(),  
                    expressions=[exp.column("ReporteeID")]
                )
                .from_("Manager_Master")
                .where(exp.column("ManagerId").eq(exp.Literal.string(user_id)))
            )
            
            if table_alias:
                condition = exp.column("GlobalUserId", table=table_alias).isin(subquery)
            else:
                condition = exp.column("GlobalUserId").isin(subquery)

            parsed = parsed.where(condition, append=True)
            return parsed.sql(pretty=True, dialect="postgres")

        return parsed.sql(pretty=True, dialect="postgres")