import pandas as pd
import numpy as np
from typing import List, Dict, Any
from app.utils.logger import logger

class PandasAnalyzerTool:
    """Executes upstream-generated Pandas math on dataframes post-SQL retrieval."""
    
    async def execute_custom_math(self, df: pd.DataFrame, python_code: str) -> List[Dict[str, Any]]:
        """Instantly executes the math script generated by the SQL Agent."""
        if df.empty or not python_code:
            return df.to_dict(orient="records")

        logger.info("Pandas Tool: Executing upstream-generated math script...")
        try:
            local_vars = {"df": df, "pd": pd, "np": np}
            
            exec(python_code, {}, local_vars)
            
            return local_vars.get("final_result", df.to_dict(orient="records"))
            
        except Exception as e:
            logger.error(f"Pandas Execution Error: {str(e)}")
            return df.to_dict(orient="records")